# Generated by Django 4.0.5 on 2022-07-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_innercategory_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/categories'),
        ),
        migrations.AddField(
            model_name='innercategory',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/categories'),
        ),
    ]
