# Generated by Django 4.0.5 on 2022-07-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_innercategory_features'),
        ('authentication', '0002_order_orderproduct_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ManyToManyField(through='authentication.OrderStore', to='store.storeproduct'),
        ),
        migrations.AddField(
            model_name='orderstore',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.order'),
        ),
        migrations.AddField(
            model_name='orderstore',
            name='storeproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeproduct'),
        ),
    ]
