# Generated by Django 4.0.5 on 2022-07-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='review_commentary',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='review',
            name='review_cons',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='review',
            name='review_pros',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
